### ISSUE TITLE
Mention datalad

### ISSUE THREAD

**Issue by gmkarl** [alpernebbi/git-annex-adapter#15]
So you know, https://github.com/datalad/datalad is a data management system that appears written in python and deeply interconnects between python and git-annex.

I'm looking into your tool because datalad seems kinda big and unwieldy for getting started small, but I was surprised not to see a reference to it.

**Comment by alpernebbi** [comment]
Added a note about it to README in c980a33, thanks. I haven't really gone through datalad's code so I don't know how useful their git-annex abstraction is when you need to use it outside datalad, though.

**Comment by xloem** [comment]
Thanks for linking these two on your end.

**Comment by gmkarl** [comment]
Thanks for this
