### ISSUE TITLE
Fetch/download annexed file?

### ISSUE THREAD

**Issue by lopsided** [alpernebbi/git-annex-adapter#18]
Hi,

I'm looking for a way to automatically fetch/download annexed files on demand if they are not present locally. Is this possible with this package?

Many thanks

**Comment by alpernebbi** [comment]
I've pushed 99b77b22 to master, which should make something like this possible now:

```
from git_annex_adapter.repo import GitAnnexRepo 
repo = GitAnnexRepo("/path/to/repo")
tree = repo.annex.get_file_tree()
foo = tree["foo.pdf"]

if foo.contentlocation is None:
    print("Getting contents for {} ...".format(foo.key))
    foo.get()
```

**Comment by lopsided** [comment]
Perfect! Thanks so much
