### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by mih** [alpernebbi/git-annex-adapter#3]
The tests included in the source do not seem to match the to-be-tested code. The use a completely different API `...Repo.make_annex()` etc. Are these meant to work?

**Comment by alpernebbi** [comment]
I guess I broke my test framework when I removed much of the git-only code (be9fb0a), and postponed rewriting the tests since then. 

I'm rewriting the project, so I'll remove the entire directory now and properly implement it from scratch.
