### ISSUE TITLE
Parsing of git_annex_version should be more flexible. 

### ISSUE THREAD

**Issue by NGenetzky** [alpernebbi/git-annex-adapter#5]
Some git-annex packages format the version in a way that is not expected by the check performed in `git_annex_adapter/__init__.py`.
```
    >>> import git_annex_adapter
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/src/app/git_annex_adapter/__init__.py", line 50, in <module>
        git_annex_version = float(version_str.split('-g', 1)[0])
    ValueError: could not convert string to float: '6.20180329+gitga5fe62bed-1~ndall+1'
```

**Comment by NGenetzky** [comment]
I fixed this issue in a single commit on my fork. I would be happy to turn it into a PR, or if you wanted to cherry-pick it.
```
commit 5f14a7ffaf3a2aad453026cbb890cf3de149937c
Author: Nathan Genetzky <nathan@genetzky.us>
Date:   Sat Apr 7 15:13:15 2018 -0500

    git_annex_adapter: Improved check_git_annex_version.
    
    This fixes issues when using a package with the "+git" append to the PV.
```

**Comment by alpernebbi** [comment]
Thanks for letting me know. I pushed 9121265 which should fix this. I guess your version works as well, but I wanted to keep the `git_annex_version` variable in the package and I don't think this will happen again, so I just used `str.split(...)[0]` twice outside a function. If there are other formats, I guess I'll use something like `float(re.match('\d+\.\d+', version_str).group(0))`.
